src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $familyName;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="client")
     */
    private $reservation;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="client")
     */
    private $comments;
    /**
     * @return string
     */
    public function __toString()
    {
        $s = '';
        $s .= $this->getId() ." ";
        $s .= $this->getFirstname() . " ";
        $s .= $this->getFamilyName();
        return $s;
    }
    public function __construct()
    {
        $this->reservation = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getFamilyName(): ?string
    {
        return $this->familyName;
    }

    public function setFamilyName(string $familyName): self
    {
        $this->familyName = $familyName;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservation(): Collection
    {
        return $this->reservation;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservation->contains($reservation)) {
            $this->reservation[] = $reservation;
            $reservation->setClient($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservation->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getClient() === $this) {
                $reservation->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setClient($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getClient() === $this) {
                $comment->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $CommentId;

    /**
     * @ORM\Column(type="text")
     */
    private $Content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="integer")
     */
    private $ReservationIdComment;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="comments")
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity=Room::class, inversedBy="comments")
     */
    private $room;
        /**
     * @return string
     */
    public function __toString()
    {
        $s = '';
        $s .= $this->getCommentId() ." ";
        $s .= $this->getContent();
        return $s;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentId(): ?int
    {
        return $this->CommentId;
    }

    public function setCommentId(int $CommentId): self
    {
        $this->CommentId = $CommentId;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getReservationIdComment(): ?int
    {
        return $this->ReservationIdComment;
    }

    public function setReservationIdComment(int $ReservationIdComment): self
    {
        $this->ReservationIdComment = $ReservationIdComment;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): self
    {
        $this->room = $room;

        return $this;
    }
}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $ReservationId;

    /**
     * @ORM\Column(type="text")
     */
    private $ReservationAdress;

    /**
     * @ORM\Column(type="integer")
     */
    private $NumberGuests;

    /**
     * @ORM\Column(type="datetime")
     */
    private $StartDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $EndDate;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $HostName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $GuestName;

    /**
     * @ORM\Column(type="integer")
     */
    private $NumberNights;

    /**
     * @ORM\Column(type="float")
     */
    private $PaymentTotal;

    /**
     * @ORM\ManyToOne(targetEntity=Room::class, inversedBy="reservations")
     */
    private $room;

    /**
     * @ORM\ManyToOne(targetEntity=UnavailablePeriod::class, inversedBy="reservations")
     */
    private $unavailablePeriod;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="reservation")
     */
    private $client;

       /**
     * @return string
     */
    public function __toString()
    {
        $s = '';
        $s .= $this->getReservationId();
  
        return $s;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReservationId(): ?int
    {
        return $this->ReservationId;
    }

    public function setReservationId(int $ReservationId): self
    {
        $this->ReservationId = $ReservationId;

        return $this;
    }

    public function getReservationAdress(): ?string
    {
        return $this->ReservationAdress;
    }

    public function setReservationAdress(string $ReservationAdress): self
    {
        $this->ReservationAdress = $ReservationAdress;

        return $this;
    }

    public function getNumberGuests(): ?int
    {
        return $this->NumberGuests;
    }

    public function setNumberGuests(int $NumberGuests): self
    {
        $this->NumberGuests = $NumberGuests;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->StartDate;
    }

    public function setStartDate(\DateTimeInterface $StartDate): self
    {
        $this->StartDate = $StartDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->EndDate;
    }

    public function setEndDate(\DateTimeInterface $EndDate): self
    {
        $this->EndDate = $EndDate;

        return $this;
    }

    public function getHostName(): ?string
    {
        return $this->HostName;
    }

    public function setHostName(string $HostName): self
    {
        $this->HostName = $HostName;

        return $this;
    }

    public function getGuestName(): ?string
    {
        return $this->GuestName;
    }

    public function setGuestName(string $GuestName): self
    {
        $this->GuestName = $GuestName;

        return $this;
    }

    public function getNumberNights(): ?int
    {
        return $this->NumberNights;
    }

    public function setNumberNights(int $NumberNights): self
    {
        $this->NumberNights = $NumberNights;

        return $this;
    }

    public function getPaymentTotal(): ?float
    {
        return $this->PaymentTotal;
    }

    public function setPaymentTotal(float $PaymentTotal): self
    {
        $this->PaymentTotal = $PaymentTotal;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): self
    {
        $this->room = $room;

        return $this;
    }

    public function getUnavailablePeriod(): ?UnavailablePeriod
    {
        return $this->unavailablePeriod;
    }

    public function setUnavailablePeriod(?UnavailablePeriod $unavailablePeriod): self
    {
        $this->unavailablePeriod = $unavailablePeriod;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname')
            ->add('familyName')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/client")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/", name="client_index", methods={"GET"})
     */
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="client_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('client/new.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="client_show", methods={"GET"})
     */
    public function show(Client $client): Response
    {
        return $this->render('client/show.html.twig', [
            'client' => $client,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="client_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Client $client): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('client/edit.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="client_delete", methods={"POST"})
     */
    public function delete(Request $request, Client $client): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($client);
            $entityManager->flush();
        }

        return $this->redirectToRoute('client_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/client/_delete_form.html.twig
<form method="post" action="{{ path('client_delete', {'id': client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn">Delete</button>
</form>

templates/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Client{% endblock %}

{% block body %}
    <h1>Edit Client</h1>

    {{ include('client/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('client_index') }}">back to list</a>

    {{ include('client/_delete_form.html.twig') }}
{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client index{% endblock %}

{% block main %}
    <h1>Client index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Firstname</th>
                <th>FamilyName</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td>{{ client.firstname }}</td>
                <td>{{ client.familyName }}</td>
                <td>
                    <a href="{{ path('client_show', {'id': client.id}) }}">show</a>
                    <a href="{{ path('client_edit', {'id': client.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('client_new') }}">Create new</a>
{% endblock %}

templates/client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Client{% endblock %}

{% block main %}
    <h1>Create new Client</h1>

    {{ include('client/_form.html.twig') }}

    <a href="{{ path('client_index') }}">back to list</a>
{% endblock %}

templates/client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client{% endblock %}

{% block body %}
    <h1>Client</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ client.id }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ client.firstname }}</td>
            </tr>
            <tr>
                <th>FamilyName</th>
                <td>{{ client.familyName }}</td>
            </tr>
            <tr>
               <th>Reservations</th>
                <td>

               {% for reservation in client.reservation %}

   <a href="{{ path('reservation_show', {'id' : reservation.reservation_id}) }}">{{ reservation.reservationId }}</a>

{% endfor %}


    <a href="{{ path('reservation_addtoclient',{'id': client.id})}}">ajouter une reservation</a>

</td>

            </tr>
            <tr>
               <th>Comments</th>
                <td>
              
               {% for comment in client.comments %}

   <a href="{{ path('comment_show', {'id' : comment.comment_id}) }}">{{ comment.content }}</a>

{% endfor %}
  <a href="{{ path('comment_addtoclient',{'id': client.id})}}">ajouter un commentaire</a>
</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('client_index') }}">back to list</a>

    <a href="{{ path('client_edit', {'id': client.id}) }}">edit</a>

    {{ include('client/_delete_form.html.twig') }}
{% endblock %}